"""Initial migration 2

Revision ID: 15af038f4128
Revises: 06a93bbce5a7
Create Date: 2025-02-03 10:16:38.457497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15af038f4128'
down_revision: Union[str, None] = '06a93bbce5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('users', 'raiting_cross_zeroes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'raiting_wordlie',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_check_constraint(
        'cross_zeroes_non_negative',
        'users',
        'cross_zeroes_rating >= 0'
    )
    op.create_check_constraint(
        'wordlie_non_negative',
        'users',
        'wordlie_rating >= 0'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'raiting_wordlie',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'raiting_cross_zeroes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_check_constraint(
        'cross_zeroes_non_negative',
        'users',
        'cross_zeroes_rating >= 0'
    )
    op.drop_check_constraint(
        'wordlie_non_negative',
        'users',
        'wordlie_rating >= 0'
    )
    # ### end Alembic commands ###
