"""Initial migration 3

Revision ID: e1d0191549d5
Revises: 15af038f4128
Create Date: 2025-02-03 10:35:39.994610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d0191549d5'
down_revision: Union[str, None] = '15af038f4128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'cross_zeroes_non_negative',
        'users',
        'raiting_cross_zeroes >= 0'
    )
    op.create_check_constraint(
        'wordlie_non_negative',
        'users',
        'raiting_wordlie >= 0'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_check_constraint(
        'cross_zeroes_non_negative',
        'users',
        'raiting_cross_zeroes >= 0'
    )
    op.drop_check_constraint(
        'wordlie_non_negative',
        'users',
        'raiting_wordlie >= 0'
    )
    # ### end Alembic commands ###
